### ISSUE TITLE
mumu模拟器12 未检测到设备

### ISSUE THREAD

**Issue by a927050047** [Miltomo/SBGT-Release#2]
请问目前支持的设备有哪些？我的电脑为windows11，使用mumu模拟器12，打开Shining BeautifulGirls.exe显示检测不到设备，隔壁明日方舟的MAA可以检测到，尝试了adb连接模拟器，链接后也检测不到。
![image](https://github.com/Miltomo/SBGT-Release/assets/57553980/fa700a47-5861-45d4-99e8-ae8fa9c1be69)

**Comment by Miltomo** [comment]
不要用命令行。任务管理器 -> 结束所有adb.exe。直接打开软件按刷新按钮自动就连接了。(为了减少连接异常)我设置了连接之前强制结束所有adb的，你用命令行也没用。

**Comment by Miltomo** [comment]
理论上支持所有Android设备。我是雷电模拟器和(小米)手机测试过，全都是正常识别的。

**Comment by a927050047** [comment]
> @a927050047 不要用命令行。任务管理器 -> 结束所有adb.exe。直接打开软件按刷新按钮自动就连接了。(为了减少连接异常)我设置了连接之前强制结束所有adb的，你用命令行也没用。

关闭所有adb进程后也找不到设备，
![image](https://github.com/Miltomo/SBGT-Release/assets/57553980/22d9ca34-6084-4060-a7eb-ab2ee3c2ab19)
搜索引擎上说mumu模拟器[默认不会连接上adb](https://ceshiren.com/t/topic/6368)，可能mumu模拟器需要额外的步骤去连接adb

**Comment by Miltomo** [comment]
> > @a927050047 不要用命令行。任务管理器 -> 结束所有adb.exe。直接打开软件按刷新按钮自动就连接了。(为了减少连接异常)我设置了连接之前强制结束所有adb的，你用命令行也没用。
> 
> 关闭所有adb进程后也找不到设备， ![image](https://private-user-images.githubusercontent.com/57553980/300053065-22d9ca34-6084-4060-a7eb-ab2ee3c2ab19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODkxNTUsIm5iZiI6MTcwNjI4ODg1NSwicGF0aCI6Ii81NzU1Mzk4MC8zMDAwNTMwNjUtMjJkOWNhMzQtNjA4NC00MDYwLWE3ZWItYWIyZWUzYzJhYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE3MDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMzk2YTZlYzdkMDc3MmE5NjY0ZDk3NGM1MGUzNWNjNmM4OGEzZjI2MTkyNjdlMGRjZjUyYWY1M2VkY2EwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.McAnVmNK_ZH_JCwwp-l10iiQ3QPRqyQcYSXYlz6rjIQ) 搜索引擎上说mumu模拟器[默认不会连接上adb](https://ceshiren.com/t/topic/6368)，可能mumu模拟器需要额外的步骤去连接adb

OK，已记录。明天我下载个MUMU试试。

**Comment by Miltomo** [comment]
@a927050047 已在新版本中修复。我这边是已经正常了
![搜狗截图20240127161427](https://github.com/Miltomo/SBGT-Release/assets/61451622/e034d688-4c98-4ad8-a2a3-dd82a795190e)

直接替换SBG.dll就行，其他都是一样的

**Comment by a927050047** [comment]
可以正常连接了，感谢

**Comment by Miltomo** [comment]
> 可以正常连接了，感谢

还有个小问题[但是会导致无法使用]，进入用户会新建ADB然后又Kill了已连接好的程序，导致MUMU这种又连不上。请使用repair2版本，预计十分钟后发布。
