### ISSUE TITLE
运行至选择好友协助卡界面后闪退

### ISSUE THREAD

**Issue by a927050047** [Miltomo/SBGT-Release#5]
![image](https://github.com/Miltomo/SBGT-Release/assets/57553980/a93ca24f-cbaa-45a4-85e0-134ef6c15995)
win11，mumu模拟器，运行到此处后闪退

**Comment by Miltomo** [comment]
是最新版本才有这个问题吗？闪退之前有没有报错信息？

**Comment by Miltomo** [comment]
@a927050047 我好像知道为什么了。你选好协助卡后，先关闭软件。再重启应该就好了。我升级数据结构后，协助卡的默认值设为了空。导致找不到该文件。有数据保存记录后就会正常的。这是个BUG，感谢反馈。

**Comment by Miltomo** [comment]
使用v1.0.1的dll替换一下试试吧

**Comment by a927050047** [comment]
可以成功运行了！感谢修复
